---
output: github_document
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# norgeo

<!-- badges: start -->
<!-- badges: end -->

The aim of `norgeo` package is to be able to track changes to the geo codes in Norway. This is based on information and tables available on SSB [website](https://www.ssb.no/befolkning/artikler-og-publikasjoner/regionale-endringer-2020). Therefore, the use of this package might be limited to the data available from SSB.

## Installation

`norgeo` package can be installed directly from **GitHub** page of [Folkehelseprofil](https://github.com/folkehelseprofil). You can run the code below for installation. It will use `remotes` package to access to the **GitHub**. If you haven't installed it before, the package will be installed automatically prior to installing `norgeo`.

``` r
if(!require(remotes)) install.packages("remotes")
remotes::install.packages("folkehelseprofil/norgeo")
```

# Example

You have to download the files from SSB and save it as a `csv` file. Else copy paste in an Excel file for code changes under *Endringer* tab. It's advisable to name the file with endring with `change`. For example `fylke_change_jan2018.xlsx`. It's also advisable to add the year to all files to easily differentiate them when running the code.

## Add code change

To merge both the `csv` and `xlsx` files, use function `add_change()` as the following:

```r
folder <- "F:/org/kommune"

kommune2018 <- add_change(grep.file = "jan2018",
                          grep.change = "change",
                          year = 2018,
                          type = "kommune",
                          folder.path = file_path)

```
