## ignore warning on no visible binding
utils::globalVariables(c("curr",
                         "currName",
                         "new",
                         "old",
                         "prev",
                         "prevName",
                         "code",
                         "V1",
                         "V2",
                         "allDT",
                         "i.code",
                         "i.year",
                         "name",
                         "precode",
                         "types",
                         "files"))
